(function(){
const files=["data/ch01-015.b64","data/ch02-030.b64","data/ch03-045.b64","data/ch04-060.b64","data/ch05-075.b64","data/ch06-090.b64","data/ch07-105.b64","data/ch08-120.b64","data/ch09-135.b64","data/ch10-150.b64","data/ch11-165.b64","data/ch12-180.b64"];
const SECTIONS=["Platform Setup and Governance","Consent Management","Data Modeling, Identity Resolution, and Segmentation","Campaigns, Flows, and Content","Agentforce and AI Innovation","Analytics and Performance Insights"];
const storeKey="mcn180_v3";
let Q=[],filtered=[],idx=0,mode="study",section="all",flipped=false,quizAnswered=false;
let state=JSON.parse(localStorage.getItem(storeKey)||'{"known":{},"review":{},"correct":{},"wrong":{}}');
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");
const md=s=>String(s).split(/\n\s*\n/).map(b=>{b=b.trim();if(!b)return"";let ls=b.split("\n");if(ls.every(x=>/^\s*-\s+/.test(x)))return"<ul>"+ls.map(x=>"<li>"+inline(x.replace(/^\s*-\s+/,""))+"</li>").join("")+"</ul>";return"<p>"+ls.map(inline).join("<br>")+"</p>"}).join("");
async function chunk(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw Error(path);const b64=(await r.text()).trim(),bin=atob(b64),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)),stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));return JSON.parse(await new Response(stream).text())}
async function init(){
  try{Q=(await Promise.all(files.map(chunk))).flat();if(Q.length!==180)throw Error("Expected 180 questions, got "+Q.length);filtered=Q.slice();renderSections();apply();}
  catch(e){$("loading").textContent="문항 데이터를 불러오지 못했습니다. 잠시 후 새로고침하세요.";console.error(e);}
}
function save(){localStorage.setItem(storeKey,JSON.stringify(state));stats();performance()}
function stats(){$("total").textContent=filtered.length;$("known").textContent=Object.values(state.known).filter(Boolean).length;$("review").textContent=Object.values(state.review).filter(Boolean).length}
function renderSections(){$("sections").innerHTML='<button class="sec active" data-s="all">All Sections</button>'+SECTIONS.map(s=>`<button class="sec" data-s="${esc(s)}">${esc(s)}</button>`).join("");document.querySelectorAll('.sec').forEach(b=>b.onclick=()=>{section=b.dataset.s;document.querySelectorAll('.sec').forEach(x=>x.classList.toggle('active',x===b));apply()})}
function apply(){let lv=$("level").value,t=$("search").value.trim().toLowerCase();filtered=Q.filter(q=>(lv==='all'||String(q.part)===lv)&&(section==='all'||q.section===section)&&(!t||(q.question+' '+q.answerText+' '+q.explanation).toLowerCase().includes(t)));idx=Math.min(idx,Math.max(0,filtered.length-1));render();stats()}
function render(){const q=filtered[idx];if(!q){$("loading").textContent="조건에 맞는 문제가 없습니다.";return}$("loading").textContent="";flipped=false;$("card").classList.remove("flip");$("num").textContent=`Q${q.id} · ${q.partName}`;$("secLabel").textContent=q.section;$("backLabel").textContent=q.partName;$("question").innerHTML=md(q.question);$("choices").innerHTML=['A','B','C','D'].map(l=>`<div class="choice"><b>${l}</b><span>${inline(q.choices[l]||'')}</span></div>`).join('');$("answer").textContent=`${q.answer}. ${q.answerText}`;$("explanation").innerHTML=md(q.explanation);$("progress").style.width=(filtered.length?(idx+1)/filtered.length*100:0)+'%'}
function next(){if(filtered.length){idx=(idx+1)%filtered.length;render()}}function prev(){if(filtered.length){idx=(idx-1+filtered.length)%filtered.length;render()}}
function mark(t){const id=qid();if(!id)return;if(t==='known'){state.known[id]=1;delete state.review[id]}else{state.review[id]=1;delete state.known[id]}save();next()}
function qid(){return filtered[idx]?.id}
function performance(){
  $("performance").innerHTML=SECTIONS.map(s=>{const a=Q.filter(q=>q.section===s),k=a.filter(q=>state.known[q.id]).length,r=a.filter(q=>state.review[q.id]).length,c=a.filter(q=>state.correct[q.id]).length,w=a.filter(q=>state.wrong[q.id]).length,p=Math.round(k/a.length*100);return `<div class="pc"><h3>${esc(s)}</h3><div class="row"><b>${k}/${a.length} Known</b><span>${p}%</span></div><div class="mini"><i style="width:${p}%"></i></div><small>Review ${r} · Quiz ✓ ${c} · Quiz ✕ ${w}</small></div>`}).join('')}
function setMode(m){mode=m;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));$("study").style.display=m==='study'?'block':'none';$("quiz").style.display=m==='quiz'?'block':'none';$("perf").style.display=m==='perf'?'block':'none';$("title").textContent=m==='study'?'Study Mode':m==='quiz'?'Quiz Mode':'Performance';if(m==='quiz')quiz();if(m==='perf')performance()}
function quiz(){const q=filtered[idx];if(!q)return;$("qnum").textContent=`Q${q.id} · ${q.partName}`;$("qsec").textContent=q.section;$("qq").innerHTML=md(q.question);$("qchoices").innerHTML=['A','B','C','D'].map(l=>`<button class="qchoice" data-l="${l}"><b>${l}</b> · ${inline(q.choices[l]||'')}</button>`).join('');$("feedback").innerHTML='';quizAnswered=false;document.querySelectorAll('.qchoice').forEach(b=>b.onclick=()=>answerQuiz(b.dataset.l))}
function answerQuiz(l){if(quizAnswered)return;quizAnswered=true;const q=filtered[idx],ok=l===q.answer;(ok?state.correct:state.wrong)[q.id]=1;document.querySelectorAll('.qchoice').forEach(b=>{if(b.dataset.l===q.answer)b.classList.add('correct');if(b.dataset.l===l&&!ok)b.classList.add('wrong');b.disabled=true});$("feedback").className='feedback '+(ok?'good':'bad');$("feedback").innerHTML=ok?`✓ Correct<br>${esc(q.answerText)}`:`✕ Incorrect<br>정답: ${esc(q.answer+'. '+q.answerText)}<div class="explain">${md(q.explanation)}</div>`;save()}
$("card").onclick=()=>{flipped=!flipped;$("card").classList.toggle('flip',flipped)};$("next").onclick=next;$("prev").onclick=prev;$("knownBtn").onclick=()=>mark('known');$("reviewBtn").onclick=()=>mark('review');$("random").onclick=()=>{idx=Math.floor(Math.random()*filtered.length);render()};$("again").onclick=()=>{filtered=Q.filter(q=>state.review[q.id]);idx=0;section='all';render()};$("reset").onclick=()=>{if(confirm('모든 학습 기록을 초기화할까요?')){state={known:{},review:{},correct:{},wrong:{}};save();render()}};$("qnext").onclick=()=>{next();quiz()};$("level").onchange=()=>{idx=0;apply()};$("search").oninput=()=>{idx=0;apply()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.addEventListener('keydown',e=>{if(e.target.matches('input,select,button'))return;if(mode==='study'){if(e.code==='Space'){e.preventDefault();$("card").click()}if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()}else if(mode==='quiz'){if('1234'.includes(e.key))answerQuiz(['A','B','C','D'][+e.key-1]);if(e.key==='ArrowRight'){next();quiz()}}});init();
})();