(function(){
"use strict";
const FILES=[
  {part:1,partName:"Easy",files:["data/ch01-015.b64","data/ch02-030.b64","data/ch03-045.b64","data/ch04-060.b64"]},
  {part:2,partName:"Intermediate",files:["data/ch05-075.b64","data/ch06-090.b64","data/ch07-105.b64","data/ch08-120.b64"]},
  {part:3,partName:"Advanced",files:["data/ch09-135.b64","data/ch10-150.b64","data/ch11-165.b64","data/ch12-180.b64"]}
];
const SECTIONS=["Platform Setup and Governance","Consent Management","Data Modeling, Identity Resolution, and Segmentation","Campaigns, Flows, and Content","Agentforce and AI Innovation","Analytics and Performance Insights"];
const LEVEL_NAMES={1:"Easy",2:"Intermediate",3:"Advanced"};const STORE_KEY="mcn180_v8";
let QUESTIONS=[],filtered=[],idx=0,mode="study",section="all",flipped=false,quizAnswered=false,level=1;
let state;try{state=JSON.parse(localStorage.getItem(STORE_KEY)||"")}catch(e){}if(!state||typeof state!=="object")state={known:{},review:{},correct:{},wrong:{}};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");
const md=s=>String(s??"").split(/\n\s*\n/).map(b=>{b=b.trim();if(!b)return"";let ls=b.split("\n").filter(Boolean);if(ls.every(x=>/^\s*-\s+/.test(x)))return"<ul>"+ls.map(x=>"<li>"+inline(x.replace(/^\s*-\s+/,'') )+"</li>").join("")+"</ul>";return"<p>"+ls.map(inline).join("<br>")+"</p>"}).join("");
function sectionForNo(n){return n<=8?SECTIONS[0]:n<=16?SECTIONS[1]:n<=31?SECTIONS[2]:n<=49?SECTIONS[3]:n<=55?SECTIONS[4]:SECTIONS[5]}
function setLoading(msg){$("loading").textContent=msg||""}
async function loadChunk(path){
 const url=new URL(path,document.baseURI).href+"?v=20260917";const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(path+" HTTP "+r.status);const text=(await r.text()).replace(/\s+/g,"");if(!text)throw new Error(path+" is empty");const binary=atob(text),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));if(!window.DecompressionStream)throw new Error("This browser does not support gzip decompression.");const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));return JSON.parse(await new Response(stream).text());
}
async function init(){try{setLoading("문항 데이터를 불러오는 중…");const groups=[];for(const group of FILES){const chunks=await Promise.all(group.files.map(loadChunk));groups.push(chunks.flat().map(q=>({...q,part:group.part,partName:group.partName,id:q.id||((group.part-1)*60+(q.no||0)),section:sectionForNo(q.no||0)})))}QUESTIONS=groups.flat().sort((a,b)=>a.id-b.id);if(QUESTIONS.length!==180)throw new Error("Expected 180 questions, got "+QUESTIONS.length);renderSections();refresh();setLoading("180개 문항 로드 완료")}catch(e){console.error(e);setLoading("문항 데이터 로드 실패: "+e.message);$("question").innerHTML="<p style='padding:40px;text-align:center;color:#6c7482'>문항 데이터를 불러오지 못했습니다.<br><br>페이지를 새로고침하세요.</p>";$("choices").innerHTML=""}}
function renderLevels(){document.querySelectorAll(".level").forEach(b=>b.classList.toggle("active",Number(b.dataset.level)===level))}
function renderSections(){$("sections").innerHTML='<button class="sec active" data-s="all">All Sections</button>'+SECTIONS.map(s=>`<button class="sec" data-s="${esc(s)}">${esc(s)}</button>`).join("");document.querySelectorAll(".sec").forEach(b=>b.onclick=()=>{section=b.dataset.s;idx=0;document.querySelectorAll(".sec").forEach(x=>x.classList.toggle("active",x===b));refresh()})}
function current(){const t=$("search").value.trim().toLowerCase();return QUESTIONS.filter(q=>q.part===level&&(section==="all"||q.section===section)&&(!t||(q.question+" "+q.answerText+" "+q.explanation).toLowerCase().includes(t)))}
function refresh(){filtered=current();if(idx>=filtered.length)idx=Math.max(0,filtered.length-1);$("title").textContent=LEVEL_NAMES[level]+" · "+(mode==="study"?"Study Mode":mode==="quiz"?"Quiz Mode":"Performance");$("subtitle").textContent=mode==="study"?"카드를 클릭해 정답과 해설을 확인하세요.":mode==="quiz"?"선택 후 결과를 확인하세요.":"학습 현황을 확인하세요.";$('total').textContent=filtered.length;$('known').textContent=Object.values(state.known).filter(Boolean).length;$('review').textContent=Object.values(state.review).filter(Boolean).length;if(mode==="study")renderStudy();else if(mode==="quiz")quiz();else performance();updateProgress()}
function updateProgress(){$("progress").style.width=(filtered.length?(idx+1)/filtered.length*100:0)+"%"}
function renderStudy(){$("study").style.display="block";$('quiz').style.display="none";$('perf').style.display="none";const q=filtered[idx];if(!q){$('question').innerHTML="";$('choices').innerHTML="";$('answer').textContent="";$('explanation').innerHTML="";return}flipped=false;$('card').classList.remove('flip');$('num').textContent=`Q${q.no} · ${q.partName}`;$('secLabel').textContent=q.section;$('backLabel').textContent=q.partName;$('question').innerHTML=md(q.question);$('choices').innerHTML=['A','B','C','D'].map(l=>`<div class="choice"><b>${l}</b><span>${inline(q.choices[l]||'')}</span></div>`).join('');$('answer').textContent=`${q.answer}. ${q.answerText}`;$('explanation').innerHTML=md(q.explanation)}
function next(){if(filtered.length){idx=(idx+1)%filtered.length;renderStudy();updateProgress()}}function prev(){if(filtered.length){idx=(idx-1+filtered.length)%filtered.length;renderStudy();updateProgress()}}
function mark(type){if(!filtered.length)return;const q=filtered[idx];if(type==='known'){state.known[q.id]=1;delete state.review[q.id]}else{state.review[q.id]=1;delete state.known[q.id]}save();next();refresh()}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function setMode(m){mode=m;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));refresh()}
function quiz(){$('study').style.display='none';$('quiz').style.display='block';$('perf').style.display='none';const q=filtered[idx];if(!q)return;$('qnum').textContent=`Q${q.no} · ${q.partName}`;$('qsec').textContent=q.section;$('qq').innerHTML=md(q.question);$('qchoices').innerHTML=['A','B','C','D'].map(l=>`<button class="qchoice" data-l="${l}"><b>${l}</b> · ${inline(q.choices[l]||'')}</button>`).join('');$('feedback').className='feedback';$('feedback').innerHTML='';quizAnswered=false;document.querySelectorAll('.qchoice').forEach(b=>b.onclick=()=>answerQuiz(b.dataset.l));$('qnext').onclick=()=>{next();quiz()}}
function answerQuiz(l){if(quizAnswered)return;quizAnswered=true;const q=filtered[idx],ok=l===q.answer;(ok?state.correct:state.wrong)[q.id]=1;document.querySelectorAll('.qchoice').forEach(b=>{if(b.dataset.l===q.answer)b.classList.add('correct');if(b.dataset.l===l&&!ok)b.classList.add('wrong');b.disabled=true});$('feedback').className='feedback '+(ok?'good':'bad');$('feedback').innerHTML=ok?`✓ Correct<br>${esc(q.answerText)}`:`✕ Incorrect<br>정답: ${esc(q.answer+'. '+q.answerText)}<div class="explain">${md(q.explanation)}</div>`;save()}
function performance(){$('study').style.display='none';$('quiz').style.display='none';$('perf').style.display='block';$('performance').innerHTML=SECTIONS.map(s=>{const a=QUESTIONS.filter(q=>q.part===level&&q.section===s),k=a.filter(q=>state.known[q.id]).length,r=a.filter(q=>state.review[q.id]).length,c=a.filter(q=>state.correct[q.id]).length,w=a.filter(q=>state.wrong[q.id]).length,p=a.length?Math.round(k/a.length*100):0;return`<div class="pc"><h3>${esc(s)}</h3><div class="row"><b>${k}/${a.length} Known</b><span>${p}%</span></div><div class="mini"><i style="width:${p}%"></i></div><small>Review ${r} · Quiz ✓ ${c} · Quiz ✕ ${w}</small></div>`}).join('')}
$('card').onclick=()=>{if(filtered.length){flipped=!flipped;$('card').classList.toggle('flip',flipped)}};$('next').onclick=next;$('prev').onclick=prev;$('knownBtn').onclick=()=>mark('known');$('reviewBtn').onclick=()=>mark('review');$('random').onclick=()=>{if(filtered.length){idx=Math.floor(Math.random()*filtered.length);refresh()}};$('again').onclick=()=>{filtered=QUESTIONS.filter(q=>state.review[q.id]);idx=0;mode='study';document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('on',b.dataset.mode==='study'));renderStudy();updateProgress();$('total').textContent=filtered.length};$('reset').onclick=()=>{if(confirm('모든 학습 기록을 초기화할까요?')){state={known:{},review:{},correct:{},wrong:{}};save();apply()}};$('search').oninput=()=>{idx=0;refresh()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('.level').forEach(b=>b.onclick=()=>{level=Number(b.dataset.level);section='all';idx=0;renderLevels();renderSections();refresh()});document.addEventListener('keydown',e=>{if(e.target.matches('input,button'))return;if(mode==='study'){if(e.code==='Space'){e.preventDefault();$('card').click()}if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()}else if(mode==='quiz'){if('1234'.includes(e.key))answerQuiz(['A','B','C','D'][+e.key-1]);if(e.key==='ArrowRight'){next();quiz()}}});renderLevels();init();
})();